/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PropertyManagementRouteImport } from './routes/property-management'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LandlordSupportRouteImport } from './routes/landlord-support'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'

const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyManagementRoute = PropertyManagementRouteImport.update({
  id: '/property-management',
  path: '/property-management',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordSupportRoute = LandlordSupportRouteImport.update({
  id: '/landlord-support',
  path: '/landlord-support',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PropertiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/landlord-support': typeof LandlordSupportRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/property-management': typeof PropertyManagementRoute
  '/services': typeof ServicesRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/properties/$slug': typeof PropertiesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/landlord-support': typeof LandlordSupportRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/property-management': typeof PropertyManagementRoute
  '/services': typeof ServicesRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/properties/$slug': typeof PropertiesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/landlord-support': typeof LandlordSupportRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/property-management': typeof PropertyManagementRoute
  '/services': typeof ServicesRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/properties/$slug': typeof PropertiesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faqs'
    | '/how-it-works'
    | '/landlord-support'
    | '/privacy-policy'
    | '/properties'
    | '/property-management'
    | '/services'
    | '/terms-of-use'
    | '/properties/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faqs'
    | '/how-it-works'
    | '/landlord-support'
    | '/privacy-policy'
    | '/properties'
    | '/property-management'
    | '/services'
    | '/terms-of-use'
    | '/properties/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faqs'
    | '/how-it-works'
    | '/landlord-support'
    | '/privacy-policy'
    | '/properties'
    | '/property-management'
    | '/services'
    | '/terms-of-use'
    | '/properties/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LandlordSupportRoute: typeof LandlordSupportRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  PropertyManagementRoute: typeof PropertyManagementRoute
  ServicesRoute: typeof ServicesRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-management': {
      id: '/property-management'
      path: '/property-management'
      fullPath: '/property-management'
      preLoaderRoute: typeof PropertyManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord-support': {
      id: '/landlord-support'
      path: '/landlord-support'
      fullPath: '/landlord-support'
      preLoaderRoute: typeof LandlordSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof PropertiesRoute
    }
  }
}

interface PropertiesRouteChildren {
  PropertiesSlugRoute: typeof PropertiesSlugRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesSlugRoute: PropertiesSlugRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  HowItWorksRoute: HowItWorksRoute,
  LandlordSupportRoute: LandlordSupportRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  PropertyManagementRoute: PropertyManagementRoute,
  ServicesRoute: ServicesRoute,
  TermsOfUseRoute: TermsOfUseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
