name: Northstone Main

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Setup npm
      uses: npm/action-setup@v4
      with:
        version: 10.23.0
        run_install: false
    - uses: actions/cache@v4
      with:
        # See here for caching with `yarn`, `bun` or other package managers https://github.com/actions/cache/blob/main/examples.md or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/npm-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/npm-lock.json') }}-
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Delete necessary files and folders
      run: |
        rm -rf node_modules
        rm -rf /var/www/nsproperties/*
    - name: Copy files to app directory and build
      run: |
        cp -r * /var/www/nsproperties && cd /var/www/nsproperties
        pm2 stop all && npm i && npm run nsproperties
        pm2 restart all
